ALTER TABLE guilds ADD COLUMN IF NOT EXISTS afk_channel_id BIGINT;
ALTER TABLE guilds ADD COLUMN IF NOT EXISTS system_channel_id BIGINT;
ALTER TABLE guilds ADD COLUMN IF NOT EXISTS verification_level INT NOT NULL DEFAULT 0;
